--SELECT city.city, country, FROM city LEFT JOIN country ON country.id = city.country_id;
--SELECT payment.id, first_name, last_name, FROM payment RIGHT JOIN customer ON customer.id = payment.customer_id;
--SELECT rental.id, first_name, last_name, FROM rental FULL JOIN customer ON customer.id = rental.customer_id;
